logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate=DEBUG

spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  application:
    name: projects-service
server:
  port: 5002
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: true
---
spring:
  profiles: dev
  data.mongodb:
    host: localhost
    port: 27017
    database: local
---
spring:
  profiles: prod
  data.mongodb:
    host: localhost
    port: 27017
    database: local
---
spring:
  profiles: test
  data.mongodb:
    host: localhost
    port: 27017
    database: local
