version: '3'

services:
  mongodb:
    container_name: neo4j_server
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    expose:
      - 27017
  rabbitmq_server:
    container_name: rabbitmq_server
    hostname: rabbitmq_server
    image: 'bitnami/rabbitmq:latest'
    environment:
      RABBITMQ_USERNAME: astra_user
      RABBITMQ_PASSWORD: astra_password
  neo4j:
    container_name: neo4j_server
    image: bitnami/neo4j:latest
    environment:
      NEO4J_PASSWORD: morgan11
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
