spring:
  application:
    name: companies-service
  cloud:
    config:
      uri: http://cloud_config_service:8000
---
spring:
  profiles: container
  datasource:
    url:
spring.
spring.datasource.url=
spring.datasource.username=root
spring.datasource.password=astra
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.cloud.stream.bindings.*.content-type=application/json

