server:
  port: 3500
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: true
spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
