server:
  port: 6000
spring:
  application:
    name: query-service
  data:
    neo4j:
      username: neo4j
      password: morgan11
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

