server:
  port: 3500
eureka:
  client:
    register-with-eureka: true
spring:
  cloud:
    gateway:
      routes:
        - id: companies-service
          uri: lb://companies-service
          predicates:
          - Path=/companies-service/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  profiles:
    active: dev
---
spring:
  profiles: dev
  data.mongodb:
    host: localhost
    port: 27017
    database: local
---
spring:
  profiles: nonprod
  data.mongodb:
    host: localhost
    port: 27017
    database: local
---
spring:
  profiles: prod
  data.mongodb:
    host: localhost
    port: 27017
    database: local

